### ISSUE TITLE
Could not find package tilleuls/amazon-mws at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by maykino** [coopTilleuls/amazon-mws#4]
I get the following error: 

<img width="1104" alt="screen shot 2016-11-18 at 12 58 15 pm" src="https://cloud.githubusercontent.com/assets/4440410/20446504/c50cafb4-ad8e-11e6-810c-bc483c269dd9.png">

**Comment by meyerbaptiste** [comment]
Yes it's normal, there is not stable version tagged currently. Run this instead: `composer install tilleuls/amazon-mws:dev-master`
