### ISSUE TITLE
GeneratedReportId

### ISSUE THREAD

**Issue by Cubicfox** [coopTilleuls/amazon-mws#6]
According to
https://docs.developer.amazonservices.com/en_UK/reports/Reports_Datatypes.html#ReportRequestInfo
there is 3 missing 'fields' from the MarketplaceWebService_Model_ReportRequestInfo
'GeneratedReportId' => ['FieldValue' => null, 'FieldType' => 'string'],
'StartedProcessingDate' => ['FieldValue' => null, 'FieldType' => 'DateTime'],
'CompletedDate' => ['FieldValue' => null, 'FieldType' => 'DateTime'],

**Comment by sroze** [comment]
PR welcomed :-)

**Comment by meyerbaptiste** [comment]
Fixed by #8.
